//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>The animation element categorizes the declaration of animation information. The animation 
    ///			hierarchy contains elements that describe the animation’s key-frame data and sampler functions, 
    ///			ordered in such a way to group together animations that should be executed together.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"The animation element categorizes the declaration of animation information. The animation hierarchy contains elements that describe the animation’s key-frame data and sampler functions, ordered in such a way to group together animations that should be executed together.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("animation", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("animation", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public partial class Animation
    {
        
        /// <summary>
        /// <para>The animation element may contain an asset element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The animation element may contain an asset element.")]
        [System.Xml.Serialization.XmlElementAttribute("asset")]
        public Asset Asset { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Source> _source;
        
        /// <summary>
        /// <para>The animation element may contain any number of source elements.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The animation element may contain any number of source elements.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("source")]
        public System.Collections.ObjectModel.Collection<Source> Source
        {
            get
            {
                return this._source;
            }
            private set
            {
                this._source = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Animation" /> class.</para>
        /// </summary>
        public Animation()
        {
            this._source = new System.Collections.ObjectModel.Collection<Source>();
            this._sampler = new System.Collections.ObjectModel.Collection<Sampler>();
            this._channel = new System.Collections.ObjectModel.Collection<Channel>();
            this._animationProperty = new System.Collections.ObjectModel.Collection<Animation>();
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Sampler> _sampler;
        
        /// <summary>
        /// <para>The animation element may contain any number of sampler elements.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The animation element may contain any number of sampler elements.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("sampler")]
        public System.Collections.ObjectModel.Collection<Sampler> Sampler
        {
            get
            {
                return this._sampler;
            }
            private set
            {
                this._sampler = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Channel> _channel;
        
        /// <summary>
        /// <para>The animation element may contain any number of channel elements.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The animation element may contain any number of channel elements.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("channel")]
        public System.Collections.ObjectModel.Collection<Channel> Channel
        {
            get
            {
                return this._channel;
            }
            private set
            {
                this._channel = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Animation> _animationProperty;
        
        /// <summary>
        /// <para>The animation may be hierarchical and may contain any number of other animation elements.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The animation may be hierarchical and may contain any number of other animation e" +
            "lements.")]
        [System.Xml.Serialization.XmlElementAttribute("animation")]
        public System.Collections.ObjectModel.Collection<Animation> AnimationProperty
        {
            get
            {
                return this._animationProperty;
            }
            private set
            {
                this._animationProperty = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AnimationProperty collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnimationPropertySpecified
        {
            get
            {
                return (this.AnimationProperty.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        /// <summary>
        /// <para>The extra element may appear any number of times.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The extra element may appear any number of times.")]
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The id attribute is a text string containing the unique identifier of this element. This value 
        ///					must be unique within the instance document. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The id attribute is a text string containing the unique identifier of this elemen" +
            "t. This value must be unique within the instance document. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        /// <summary>
        /// <para>The name attribute is the text string name of this element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The name attribute is the text string name of this element. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
}
