//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AssetContributor", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssetContributor
    {
        
        /// <summary>
        /// <para>The author element contains a string with the author's name.
        ///									There may be only one author element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The author element contains a string with the author\'s name. There may be only on" +
            "e author element.")]
        [System.Xml.Serialization.XmlElementAttribute("author")]
        public string Author { get; set; }
        
        /// <summary>
        /// <para>The authoring_tool element contains a string with the authoring tool's name.
        ///									There may be only one authoring_tool element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The authoring_tool element contains a string with the authoring tool\'s name. Ther" +
            "e may be only one authoring_tool element.")]
        [System.Xml.Serialization.XmlElementAttribute("authoring_tool")]
        public string Authoring_Tool { get; set; }
        
        /// <summary>
        /// <para>The comments element contains a string with comments from this contributor.
        ///									There may be only one comments element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The comments element contains a string with comments from this contributor. There" +
            " may be only one comments element.")]
        [System.Xml.Serialization.XmlElementAttribute("comments")]
        public string Comments { get; set; }
        
        /// <summary>
        /// <para>The copyright element contains a string with copyright information.
        ///									There may be only one copyright element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The copyright element contains a string with copyright information. There may be " +
            "only one copyright element.")]
        [System.Xml.Serialization.XmlElementAttribute("copyright")]
        public string Copyright { get; set; }
        
        /// <summary>
        /// <para>The source_data element contains a URI reference to the source data used for this asset.
        ///									There may be only one source_data element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The source_data element contains a URI reference to the source data used for this" +
            " asset. There may be only one source_data element.")]
        [System.Xml.Serialization.XmlElementAttribute("source_data")]
        public string Source_Data { get; set; }
    }
}
