//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CameraOpticsTechnique_Common", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CameraOpticsTechnique_Common
    {
        
        /// <summary>
        /// <para>The orthographic element describes the field of view of an orthographic camera.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The orthographic element describes the field of view of an orthographic camera.")]
        [System.Xml.Serialization.XmlElementAttribute("orthographic")]
        public CameraOpticsTechnique_CommonOrthographic Orthographic { get; set; }
        
        /// <summary>
        /// <para>The perspective element describes the optics of a perspective camera.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The perspective element describes the optics of a perspective camera.")]
        [System.Xml.Serialization.XmlElementAttribute("perspective")]
        public CameraOpticsTechnique_CommonPerspective Perspective { get; set; }
    }
}
