//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>The include element is used to import source code or precompiled binary shaders into the FX Runtime by referencing an external resource.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The include element is used to import source code or precompiled binary shaders i" +
        "nto the FX Runtime by referencing an external resource.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("fx_include_common", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fx_Include_Common
    {
        
        /// <summary>
        /// <para>The sid attribute is a text string value containing the sub-identifier of this element. 
        ///					This value must be unique within the scope of the parent element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The sid attribute is a text string value containing the sub-identifier of this el" +
            "ement. This value must be unique within the scope of the parent element. Optiona" +
            "l attribute.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("sid")]
        public string Sid { get; set; }
        
        /// <summary>
        /// <para>The url attribute refers to resource.  This may refer to a local resource using a relative URL 
        ///					fragment identifier that begins with the “#” character. The url attribute may refer to an external 
        ///					resource using an absolute or relative URL.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The url attribute refers to resource. This may refer to a local resource using a " +
            "relative URL fragment identifier that begins with the “#” character. The url att" +
            "ribute may refer to an external resource using an absolute or relative URL.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("url")]
        public string Url { get; set; }
    }
}
