//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>Additional hints about data relationships and other things to help the application pick the best format.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Additional hints about data relationships and other things to help the applicatio" +
        "n pick the best format.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("fx_surface_format_hint_option_enum", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public enum Fx_Surface_Format_Hint_Option_Enum
    {
        
        /// <summary>
        /// <para>colors are stored with respect to the sRGB 2.2 gamma curve rather than linear</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("colors are stored with respect to the sRGB 2.2 gamma curve rather than linear")]
        SRGB_GAMMA,
        
        /// <summary>
        /// <para>the texel's XYZ/RGB should be normalized such as in a normal map.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("the texel\'s XYZ/RGB should be normalized such as in a normal map.")]
        NORMALIZED3,
        
        /// <summary>
        /// <para>the texel's XYZW/RGBA should be normalized such as in a normal map.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("the texel\'s XYZW/RGBA should be normalized such as in a normal map.")]
        NORMALIZED4,
        
        /// <summary>
        /// <para>The surface may use run-time compression.  Considering the best compression based on desired, channel, range, precision, and options</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The surface may use run-time compression. Considering the best compression based " +
            "on desired, channel, range, precision, and options")]
        COMPRESSABLE,
    }
}
