//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("fx_surface_init_volume_common", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fx_Surface_Init_Volume_Common
    {
        
        /// <summary>
        /// <para>Init the entire surface with one compound image such as DDS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Init the entire surface with one compound image such as DDS")]
        [System.Xml.Serialization.XmlElementAttribute("all")]
        public Fx_Surface_Init_Volume_CommonAll All { get; set; }
        
        /// <summary>
        /// <para>Init mip level 0 of the surface with one compound image such as DDS.  Use of this element expects that the surface has element mip_levels=0 or mipmap_generate.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Init mip level 0 of the surface with one compound image such as DDS. Use of this " +
            "element expects that the surface has element mip_levels=0 or mipmap_generate.")]
        [System.Xml.Serialization.XmlElementAttribute("primary")]
        public Fx_Surface_Init_Volume_CommonPrimary Primary { get; set; }
    }
}
