//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>A texture sampler for depth maps.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A texture sampler for depth maps.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("fx_samplerDEPTH_common", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cg_SamplerDEPTH))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gl_SamplerDEPTH))]
    public partial class Fx_SamplerDEPTH_Common
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("source")]
        public string Source { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Fx_Sampler_Wrap_Common _wrap_S = Collada141.Fx_Sampler_Wrap_Common.WRAP;
        
        [System.ComponentModel.DefaultValueAttribute(Collada141.Fx_Sampler_Wrap_Common.WRAP)]
        [System.Xml.Serialization.XmlElementAttribute("wrap_s")]
        public Fx_Sampler_Wrap_Common Wrap_S
        {
            get
            {
                return this._wrap_S;
            }
            set
            {
                this._wrap_S = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Fx_Sampler_Wrap_Common _wrap_T = Collada141.Fx_Sampler_Wrap_Common.WRAP;
        
        [System.ComponentModel.DefaultValueAttribute(Collada141.Fx_Sampler_Wrap_Common.WRAP)]
        [System.Xml.Serialization.XmlElementAttribute("wrap_t")]
        public Fx_Sampler_Wrap_Common Wrap_T
        {
            get
            {
                return this._wrap_T;
            }
            set
            {
                this._wrap_T = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Fx_Sampler_Filter_Common _minfilter = Collada141.Fx_Sampler_Filter_Common.NONE;
        
        [System.ComponentModel.DefaultValueAttribute(Collada141.Fx_Sampler_Filter_Common.NONE)]
        [System.Xml.Serialization.XmlElementAttribute("minfilter")]
        public Fx_Sampler_Filter_Common Minfilter
        {
            get
            {
                return this._minfilter;
            }
            set
            {
                this._minfilter = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Fx_Sampler_Filter_Common _magfilter = Collada141.Fx_Sampler_Filter_Common.NONE;
        
        [System.ComponentModel.DefaultValueAttribute(Collada141.Fx_Sampler_Filter_Common.NONE)]
        [System.Xml.Serialization.XmlElementAttribute("magfilter")]
        public Fx_Sampler_Filter_Common Magfilter
        {
            get
            {
                return this._magfilter;
            }
            set
            {
                this._magfilter = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Fx_SamplerDEPTH_Common" /> class.</para>
        /// </summary>
        public Fx_SamplerDEPTH_Common()
        {
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
    }
}
