//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("gles_texcombiner_argumentRGB_type", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Gles_Texcombiner_ArgumentRGB_Type
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("source")]
        public Gles_Texcombiner_Source_Enums Source { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Source property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Gles_Texcombiner_OperandRGB_Enums _operand = Collada141.Gles_Texcombiner_OperandRGB_Enums.SRC_COLOR;
        
        [System.ComponentModel.DefaultValueAttribute(Collada141.Gles_Texcombiner_OperandRGB_Enums.SRC_COLOR)]
        [System.Xml.Serialization.XmlAttributeAttribute("operand")]
        public Gles_Texcombiner_OperandRGB_Enums Operand
        {
            get
            {
                return this._operand;
            }
            set
            {
                this._operand = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("unit")]
        public string Unit { get; set; }
    }
}
