//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>The common set of initalization options for surfaces.  Choose which is appropriate for your surface based on type and other characteristics. described by the annotation docs on the child elements.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The common set of initalization options for surfaces. Choose which is appropriate" +
        " for your surface based on type and other characteristics. described by the anno" +
        "tation docs on the child elements.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    public partial interface IFx_Surface_Init_Common
    {
        
        /// <summary>
        /// <para>This surface is intended to be initialized later externally by a "setparam" element.  If it is used before being initialized there is profile and platform specific behavior.  Most elements on the surface element containing this will be ignored including mip_levels, mipmap_generate, size, viewport_ratio, and format.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"This surface is intended to be initialized later externally by a ""setparam"" element. If it is used before being initialized there is profile and platform specific behavior. Most elements on the surface element containing this will be ignored including mip_levels, mipmap_generate, size, viewport_ratio, and format.")]
        object Init_As_Null
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Init as a target for depth, stencil, or color.  It does not need image data. Surface should not have mipmap_generate when using this.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Init as a target for depth, stencil, or color. It does not need image data. Surfa" +
            "ce should not have mipmap_generate when using this.")]
        object Init_As_Target
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Init a CUBE from a compound image such as DDS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Init a CUBE from a compound image such as DDS")]
        Fx_Surface_Init_Cube_Common Init_Cube
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Init a 3D from a compound image such as DDS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Init a 3D from a compound image such as DDS")]
        Fx_Surface_Init_Volume_Common Init_Volume
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Init a 1D,2D,RECT,DEPTH from a compound image such as DDS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Init a 1D,2D,RECT,DEPTH from a compound image such as DDS")]
        Fx_Surface_Init_Planar_Common Init_Planar
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>Initialize the surface one sub-surface at a time by specifying combinations of mip, face, and slice which make sense for a particular surface type.  Each sub-surface is initialized by a common 2D image, not a complex compound image such as DDS. If not all subsurfaces are initialized, it is invalid and will result in profile and platform specific behavior unless mipmap_generate is responsible for initializing the remainder of the sub-surfaces</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Initialize the surface one sub-surface at a time by specifying combinations of mip, face, and slice which make sense for a particular surface type. Each sub-surface is initialized by a common 2D image, not a complex compound image such as DDS. If not all subsurfaces are initialized, it is invalid and will result in profile and platform specific behavior unless mipmap_generate is responsible for initializing the remainder of the sub-surfaces")]
        System.Collections.ObjectModel.Collection<Fx_Surface_Init_From_Common> Init_From
        {
            get;
        }
    }
}
