//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>A group that defines all of the renderstates used for the CG and GLSL profiles.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("A group that defines all of the renderstates used for the CG and GLSL profiles.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    public partial interface IGl_Pipeline_Settings
    {
        
        Gl_Pipeline_SettingsAlpha_Func Alpha_Func
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsBlend_Func Blend_Func
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsBlend_Func_Separate Blend_Func_Separate
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsBlend_Equation Blend_Equation
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsBlend_Equation_Separate Blend_Equation_Separate
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsColor_Material Color_Material
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsCull_Face Cull_Face
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsDepth_Func Depth_Func
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsFog_Mode Fog_Mode
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsFog_Coord_Src Fog_Coord_Src
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsFront_Face Front_Face
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Model_Color_Control Light_Model_Color_Control
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLogic_Op Logic_Op
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPolygon_Mode Polygon_Mode
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsShade_Model Shade_Model
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsStencil_Func Stencil_Func
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsStencil_Op Stencil_Op
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsStencil_Func_Separate Stencil_Func_Separate
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsStencil_Op_Separate Stencil_Op_Separate
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsStencil_Mask_Separate Stencil_Mask_Separate
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Enable Light_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Ambient Light_Ambient
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Diffuse Light_Diffuse
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Specular Light_Specular
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Position Light_Position
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Constant_Attenuation Light_Constant_Attenuation
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Linear_Attenuation Light_Linear_Attenuation
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Quadratic_Attenuation Light_Quadratic_Attenuation
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Spot_Cutoff Light_Spot_Cutoff
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Spot_Direction Light_Spot_Direction
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Spot_Exponent Light_Spot_Exponent
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTexture1D Texture1D
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTexture2D Texture2D
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTexture3D Texture3D
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTextureCUBE TextureCUBE
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTextureRECT TextureRECT
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTextureDEPTH TextureDEPTH
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTexture1D_Enable Texture1D_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTexture2D_Enable Texture2D_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTexture3D_Enable Texture3D_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTextureCUBE_Enable TextureCUBE_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTextureRECT_Enable TextureRECT_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTextureDEPTH_Enable TextureDEPTH_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTexture_Env_Color Texture_Env_Color
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsTexture_Env_Mode Texture_Env_Mode
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsClip_Plane Clip_Plane
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsClip_Plane_Enable Clip_Plane_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsBlend_Color Blend_Color
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsClear_Color Clear_Color
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsClear_Stencil Clear_Stencil
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsClear_Depth Clear_Depth
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsColor_Mask Color_Mask
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsDepth_Bounds Depth_Bounds
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsDepth_Mask Depth_Mask
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsDepth_Range Depth_Range
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsFog_Density Fog_Density
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsFog_Start Fog_Start
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsFog_End Fog_End
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsFog_Color Fog_Color
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Model_Ambient Light_Model_Ambient
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLighting_Enable Lighting_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLine_Stipple Line_Stipple
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLine_Width Line_Width
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsMaterial_Ambient Material_Ambient
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsMaterial_Diffuse Material_Diffuse
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsMaterial_Emission Material_Emission
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsMaterial_Shininess Material_Shininess
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsMaterial_Specular Material_Specular
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsModel_View_Matrix Model_View_Matrix
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPoint_Distance_Attenuation Point_Distance_Attenuation
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPoint_Fade_Threshold_Size Point_Fade_Threshold_Size
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPoint_Size Point_Size
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPoint_Size_Min Point_Size_Min
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPoint_Size_Max Point_Size_Max
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPolygon_Offset Polygon_Offset
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsProjection_Matrix Projection_Matrix
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsScissor Scissor
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsStencil_Mask Stencil_Mask
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsAlpha_Test_Enable Alpha_Test_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsAuto_Normal_Enable Auto_Normal_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsBlend_Enable Blend_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsColor_Logic_Op_Enable Color_Logic_Op_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsColor_Material_Enable Color_Material_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsCull_Face_Enable Cull_Face_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsDepth_Bounds_Enable Depth_Bounds_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsDepth_Clamp_Enable Depth_Clamp_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsDepth_Test_Enable Depth_Test_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsDither_Enable Dither_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsFog_Enable Fog_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Model_Local_Viewer_Enable Light_Model_Local_Viewer_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLight_Model_Two_Side_Enable Light_Model_Two_Side_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLine_Smooth_Enable Line_Smooth_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLine_Stipple_Enable Line_Stipple_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsLogic_Op_Enable Logic_Op_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsMultisample_Enable Multisample_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsNormalize_Enable Normalize_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPoint_Smooth_Enable Point_Smooth_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPolygon_Offset_Fill_Enable Polygon_Offset_Fill_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPolygon_Offset_Line_Enable Polygon_Offset_Line_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPolygon_Offset_Point_Enable Polygon_Offset_Point_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPolygon_Smooth_Enable Polygon_Smooth_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsPolygon_Stipple_Enable Polygon_Stipple_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsRescale_Normal_Enable Rescale_Normal_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsSample_Alpha_To_Coverage_Enable Sample_Alpha_To_Coverage_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsSample_Alpha_To_One_Enable Sample_Alpha_To_One_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsSample_Coverage_Enable Sample_Coverage_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsScissor_Test_Enable Scissor_Test_Enable
        {
            get;
            set;
        }
        
        Gl_Pipeline_SettingsStencil_Test_Enable Stencil_Test_Enable
        {
            get;
            set;
        }
        
        object Gl_Hook_Abstract
        {
            get;
            set;
        }
    }
}
