//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Instance_MaterialBind", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Instance_MaterialBind
    {
        
        /// <summary>
        /// <para>The semantic attribute specifies which effect parameter to bind.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The semantic attribute specifies which effect parameter to bind.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("semantic")]
        public string Semantic { get; set; }
        
        /// <summary>
        /// <para>The target attribute specifies the location of the value to bind to the specified semantic. 
        ///								This text string is a path-name following a simple syntax described in the “Addressing Syntax” 
        ///								section.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The target attribute specifies the location of the value to bind to the specified" +
            " semantic. This text string is a path-name following a simple syntax described i" +
            "n the “Addressing Syntax” section.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("target")]
        public string Target { get; set; }
    }
}
