//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Profile_GLSLTechnique", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Profile_GLSLTechnique
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Fx_Annotate_Common> _annotate;
        
        [System.Xml.Serialization.XmlElementAttribute("annotate")]
        public System.Collections.ObjectModel.Collection<Fx_Annotate_Common> Annotate
        {
            get
            {
                return this._annotate;
            }
            private set
            {
                this._annotate = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Annotate collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotateSpecified
        {
            get
            {
                return (this.Annotate.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Profile_GLSLTechnique" /> class.</para>
        /// </summary>
        public Profile_GLSLTechnique()
        {
            this._annotate = new System.Collections.ObjectModel.Collection<Fx_Annotate_Common>();
            this._code = new System.Collections.ObjectModel.Collection<Fx_Code_Profile>();
            this._include = new System.Collections.ObjectModel.Collection<Fx_Include_Common>();
            this._image = new System.Collections.ObjectModel.Collection<Image>();
            this._newparam = new System.Collections.ObjectModel.Collection<Glsl_Newparam>();
            this._setparam = new System.Collections.ObjectModel.Collection<Glsl_Setparam>();
            this._pass = new System.Collections.ObjectModel.Collection<Profile_GLSLTechniquePass>();
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Fx_Code_Profile> _code;
        
        [System.Xml.Serialization.XmlElementAttribute("code")]
        public System.Collections.ObjectModel.Collection<Fx_Code_Profile> Code
        {
            get
            {
                return this._code;
            }
            private set
            {
                this._code = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Code collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified
        {
            get
            {
                return (this.Code.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Fx_Include_Common> _include;
        
        [System.Xml.Serialization.XmlElementAttribute("include")]
        public System.Collections.ObjectModel.Collection<Fx_Include_Common> Include
        {
            get
            {
                return this._include;
            }
            private set
            {
                this._include = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Include collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeSpecified
        {
            get
            {
                return (this.Include.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Image> _image;
        
        [System.Xml.Serialization.XmlElementAttribute("image")]
        public System.Collections.ObjectModel.Collection<Image> Image
        {
            get
            {
                return this._image;
            }
            private set
            {
                this._image = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Image collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageSpecified
        {
            get
            {
                return (this.Image.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Glsl_Newparam> _newparam;
        
        [System.Xml.Serialization.XmlElementAttribute("newparam")]
        public System.Collections.ObjectModel.Collection<Glsl_Newparam> Newparam
        {
            get
            {
                return this._newparam;
            }
            private set
            {
                this._newparam = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Newparam collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewparamSpecified
        {
            get
            {
                return (this.Newparam.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Glsl_Setparam> _setparam;
        
        [System.Xml.Serialization.XmlElementAttribute("setparam")]
        public System.Collections.ObjectModel.Collection<Glsl_Setparam> Setparam
        {
            get
            {
                return this._setparam;
            }
            private set
            {
                this._setparam = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Setparam collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SetparamSpecified
        {
            get
            {
                return (this.Setparam.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Profile_GLSLTechniquePass> _pass;
        
        /// <summary>
        /// <para>A static declaration of all the render states, shaders, and settings for one rendering pipeline.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A static declaration of all the render states, shaders, and settings for one rend" +
            "ering pipeline.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pass")]
        public System.Collections.ObjectModel.Collection<Profile_GLSLTechniquePass> Pass
        {
            get
            {
                return this._pass;
            }
            private set
            {
                this._pass = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The id attribute is a text string containing the unique identifier of this element. 
        ///								This value must be unique within the instance document. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The id attribute is a text string containing the unique identifier of this elemen" +
            "t. This value must be unique within the instance document. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        /// <summary>
        /// <para>The sid attribute is a text string value containing the sub-identifier of this element. 
        ///								This value must be unique within the scope of the parent element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The sid attribute is a text string value containing the sub-identifier of this el" +
            "ement. This value must be unique within the scope of the parent element. Optiona" +
            "l attribute.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("sid")]
        public string Sid { get; set; }
    }
}
