//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>The sampler element declares an N-dimensional function used for animation. Animation function curves 
    ///			are represented by 1-D sampler elements in COLLADA. The sampler defines sampling points and how to 
    ///			interpolate between them.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The sampler element declares an N-dimensional function used for animation. Animat" +
        "ion function curves are represented by 1-D sampler elements in COLLADA. The samp" +
        "ler defines sampling points and how to interpolate between them.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sampler", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("sampler", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public partial class Sampler
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<InputLocal> _input;
        
        /// <summary>
        /// <para>The input element must occur at least one time. These inputs are local inputs.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The input element must occur at least one time. These inputs are local inputs.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("input")]
        public System.Collections.ObjectModel.Collection<InputLocal> Input
        {
            get
            {
                return this._input;
            }
            private set
            {
                this._input = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Sampler" /> class.</para>
        /// </summary>
        public Sampler()
        {
            this._input = new System.Collections.ObjectModel.Collection<InputLocal>();
        }
        
        /// <summary>
        /// <para>The id attribute is a text string containing the unique identifier of this element. This value 
        ///					must be unique within the instance document. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The id attribute is a text string containing the unique identifier of this elemen" +
            "t. This value must be unique within the instance document. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
}
