//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SkinVertex_Weights", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SkinVertex_Weights
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<InputLocalOffset> _input;
        
        /// <summary>
        /// <para>The input element must occur at least twice.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The input element must occur at least twice.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("input")]
        public System.Collections.ObjectModel.Collection<InputLocalOffset> Input
        {
            get
            {
                return this._input;
            }
            private set
            {
                this._input = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SkinVertex_Weights" /> class.</para>
        /// </summary>
        public SkinVertex_Weights()
        {
            this._input = new System.Collections.ObjectModel.Collection<InputLocalOffset>();
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
        
        /// <summary>
        /// <para>The vcount element contains a list of integers describing the number of influences for each vertex.
        ///									The vcount element may occur once.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The vcount element contains a list of integers describing the number of influence" +
            "s for each vertex. The vcount element may occur once.")]
        [System.Xml.Serialization.XmlElementAttribute("vcount")]
        public string Vcount { get; set; }
        
        /// <summary>
        /// <para>The v element describes which bones and attributes are associated with each vertex.  An index 
        ///									of –1 into the array of joints refers to the bind shape.  Weights should be normalized before use.
        ///									The v element must occur zero or one times.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The v element describes which bones and attributes are associated with each verte" +
            "x. An index of –1 into the array of joints refers to the bind shape. Weights sho" +
            "uld be normalized before use. The v element must occur zero or one times.")]
        [System.Xml.Serialization.XmlElementAttribute("v")]
        public string V { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        /// <summary>
        /// <para>The extra element may appear any number of times.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The extra element may appear any number of times.")]
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The count attribute describes the number of vertices in the base mesh. Required element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The count attribute describes the number of vertices in the base mesh. Required e" +
            "lement.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("count")]
        public ulong Count { get; set; }
    }
}
