//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>The source element declares a data repository that provides values according to the semantics of an 
    ///			input element that refers to it.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The source element declares a data repository that provides values according to t" +
        "he semantics of an input element that refers to it.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("source", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("source", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public partial class Source
    {
        
        /// <summary>
        /// <para>The source element may contain an asset element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The source element may contain an asset element.")]
        [System.Xml.Serialization.XmlElementAttribute("asset")]
        public Asset Asset { get; set; }
        
        /// <summary>
        /// <para>The source element may contain an IDREF_array.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The source element may contain an IDREF_array.")]
        [System.Xml.Serialization.XmlElementAttribute("IDREF_array")]
        public IDREF_Array IDREF_Array { get; set; }
        
        /// <summary>
        /// <para>The source element may contain a Name_array.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The source element may contain a Name_array.")]
        [System.Xml.Serialization.XmlElementAttribute("Name_array")]
        public Name_Array Name_Array { get; set; }
        
        /// <summary>
        /// <para>The source element may contain a bool_array.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The source element may contain a bool_array.")]
        [System.Xml.Serialization.XmlElementAttribute("bool_array")]
        public Bool_Array Bool_Array { get; set; }
        
        /// <summary>
        /// <para>The source element may contain a float_array.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The source element may contain a float_array.")]
        [System.Xml.Serialization.XmlElementAttribute("float_array")]
        public Float_Array Float_Array { get; set; }
        
        /// <summary>
        /// <para>The source element may contain an int_array.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The source element may contain an int_array.")]
        [System.Xml.Serialization.XmlElementAttribute("int_array")]
        public Int_Array Int_Array { get; set; }
        
        /// <summary>
        /// <para>The technique common specifies the common method for accessing this source element's data.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The technique common specifies the common method for accessing this source elemen" +
            "t\'s data.")]
        [System.Xml.Serialization.XmlElementAttribute("technique_common")]
        public SourceTechnique_Common Technique_Common { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Technique> _technique;
        
        /// <summary>
        /// <para>This element may contain any number of non-common profile techniques.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("This element may contain any number of non-common profile techniques.")]
        [System.Xml.Serialization.XmlElementAttribute("technique")]
        public System.Collections.ObjectModel.Collection<Technique> Technique
        {
            get
            {
                return this._technique;
            }
            private set
            {
                this._technique = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Technique collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TechniqueSpecified
        {
            get
            {
                return (this.Technique.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Source" /> class.</para>
        /// </summary>
        public Source()
        {
            this._technique = new System.Collections.ObjectModel.Collection<Technique>();
        }
        
        /// <summary>
        /// <para>The id attribute is a text string containing the unique identifier of this element. 
        ///					This value must be unique within the instance document. Required attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The id attribute is a text string containing the unique identifier of this elemen" +
            "t. This value must be unique within the instance document. Required attribute.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        /// <summary>
        /// <para>The name attribute is the text string name of this element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The name attribute is the text string name of this element. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
}
