//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>The visual_scene element declares the base of the visual_scene hierarchy or scene graph. The 
    ///			scene contains elements that comprise much of the visual and transformational information 
    ///			content as created by the authoring tools.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The visual_scene element declares the base of the visual_scene hierarchy or scene" +
        " graph. The scene contains elements that comprise much of the visual and transfo" +
        "rmational information content as created by the authoring tools.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("visual_scene", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("visual_scene", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public partial class Visual_Scene
    {
        
        /// <summary>
        /// <para>The visual_scene element may contain an asset element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The visual_scene element may contain an asset element.")]
        [System.Xml.Serialization.XmlElementAttribute("asset")]
        public Asset Asset { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Node> _node;
        
        /// <summary>
        /// <para>The visual_scene element must have at least one node element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The visual_scene element must have at least one node element.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public System.Collections.ObjectModel.Collection<Node> Node
        {
            get
            {
                return this._node;
            }
            private set
            {
                this._node = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Visual_Scene" /> class.</para>
        /// </summary>
        public Visual_Scene()
        {
            this._node = new System.Collections.ObjectModel.Collection<Node>();
            this._evaluate_Scene = new System.Collections.ObjectModel.Collection<Visual_SceneEvaluate_Scene>();
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Visual_SceneEvaluate_Scene> _evaluate_Scene;
        
        /// <summary>
        /// <para>The evaluate_scene element declares information specifying a specific way to evaluate this 
        ///						visual_scene. There may be any number of evaluate_scene elements.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The evaluate_scene element declares information specifying a specific way to eval" +
            "uate this visual_scene. There may be any number of evaluate_scene elements.")]
        [System.Xml.Serialization.XmlElementAttribute("evaluate_scene")]
        public System.Collections.ObjectModel.Collection<Visual_SceneEvaluate_Scene> Evaluate_Scene
        {
            get
            {
                return this._evaluate_Scene;
            }
            private set
            {
                this._evaluate_Scene = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Evaluate_Scene collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Evaluate_SceneSpecified
        {
            get
            {
                return (this.Evaluate_Scene.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        /// <summary>
        /// <para>The extra element may appear any number of times.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The extra element may appear any number of times.")]
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The id attribute is a text string containing the unique identifier of this element. This 
        ///					value must be unique within the instance document. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The id attribute is a text string containing the unique identifier of this elemen" +
            "t. This value must be unique within the instance document. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        /// <summary>
        /// <para>The name attribute is the text string name of this element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The name attribute is the text string name of this element. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
}
