//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>Declares a resource that can be used both as the source for texture samples and as the target of a rendering pass.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Declares a resource that can be used both as the source for texture samples and a" +
        "s the target of a rendering pass.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("cg_surface_type", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cg_Surface_Type : Fx_Surface_Common
    {
        
        /// <summary>
        /// <para>A procedural surface generator for the cg profile.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A procedural surface generator for the cg profile.")]
        [System.Xml.Serialization.XmlElementAttribute("generator")]
        public Cg_Surface_TypeGenerator Generator { get; set; }
    }
}
