//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>Each channel of the texel has a precision.  Typically these are all linked together.  An exact format lay lower the precision of an individual channel but applying a higher precision by linking the channels together may still convey the same information.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Each channel of the texel has a precision. Typically these are all linked togethe" +
        "r. An exact format lay lower the precision of an individual channel but applying" +
        " a higher precision by linking the channels together may still convey the same i" +
        "nformation.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("fx_surface_format_hint_precision_enum", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public enum Fx_Surface_Format_Hint_Precision_Enum
    {
        
        /// <summary>
        /// <para>For integers this typically represents 8 bits.  For floats typically 16 bits.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("For integers this typically represents 8 bits. For floats typically 16 bits.")]
        LOW,
        
        /// <summary>
        /// <para>For integers this typically represents 8 to 24 bits.  For floats typically 16 to 32 bits.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("For integers this typically represents 8 to 24 bits. For floats typically 16 to 3" +
            "2 bits.")]
        MID,
        
        /// <summary>
        /// <para>For integers this typically represents 16 to 32 bits.  For floats typically 24 to 32 bits.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("For integers this typically represents 16 to 32 bits. For floats typically 24 to " +
            "32 bits.")]
        HIGH,
    }
}
