//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LightTechnique_CommonSpot", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LightTechnique_CommonSpot
    {
        
        /// <summary>
        /// <para>The color element contains three floating point numbers specifying the color of the light.
        ///												The color element must occur exactly once.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The color element contains three floating point numbers specifying the color of t" +
            "he light. The color element must occur exactly once.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("color")]
        public TargetableFloat3 Color { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TargetableFloat _constant_Attenuation = new Collada141.TargetableFloat { Value = 1D };
        
        /// <summary>
        /// <para>The constant_attenuation is used to calculate the total attenuation of this light given a distance. 
        ///												The equation used is A = constant_attenuation + Dist*linear_attenuation + Dist^2*quadratic_attenuation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The constant_attenuation is used to calculate the total attenuation of this light" +
            " given a distance. The equation used is A = constant_attenuation + Dist*linear_a" +
            "ttenuation + Dist^2*quadratic_attenuation.")]
        [System.Xml.Serialization.XmlElementAttribute("constant_attenuation")]
        public TargetableFloat Constant_Attenuation
        {
            get
            {
                return this._constant_Attenuation;
            }
            set
            {
                this._constant_Attenuation = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TargetableFloat _linear_Attenuation = new Collada141.TargetableFloat { Value = 0D };
        
        /// <summary>
        /// <para>The linear_attenuation is used to calculate the total attenuation of this light given a distance. 
        ///												The equation used is A = constant_attenuation + Dist*linear_attenuation + Dist^2*quadratic_attenuation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The linear_attenuation is used to calculate the total attenuation of this light g" +
            "iven a distance. The equation used is A = constant_attenuation + Dist*linear_att" +
            "enuation + Dist^2*quadratic_attenuation.")]
        [System.Xml.Serialization.XmlElementAttribute("linear_attenuation")]
        public TargetableFloat Linear_Attenuation
        {
            get
            {
                return this._linear_Attenuation;
            }
            set
            {
                this._linear_Attenuation = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TargetableFloat _quadratic_Attenuation = new Collada141.TargetableFloat { Value = 0D };
        
        /// <summary>
        /// <para>The quadratic_attenuation is used to calculate the total attenuation of this light given a distance. 
        ///												The equation used is A = constant_attenuation + Dist*linear_attenuation + Dist^2*quadratic_attenuation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The quadratic_attenuation is used to calculate the total attenuation of this ligh" +
            "t given a distance. The equation used is A = constant_attenuation + Dist*linear_" +
            "attenuation + Dist^2*quadratic_attenuation.")]
        [System.Xml.Serialization.XmlElementAttribute("quadratic_attenuation")]
        public TargetableFloat Quadratic_Attenuation
        {
            get
            {
                return this._quadratic_Attenuation;
            }
            set
            {
                this._quadratic_Attenuation = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TargetableFloat _falloff_Angle = new Collada141.TargetableFloat { Value = 180D };
        
        /// <summary>
        /// <para>The falloff_angle is used to specify the amount of attenuation based on the direction of the light.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The falloff_angle is used to specify the amount of attenuation based on the direc" +
            "tion of the light.")]
        [System.Xml.Serialization.XmlElementAttribute("falloff_angle")]
        public TargetableFloat Falloff_Angle
        {
            get
            {
                return this._falloff_Angle;
            }
            set
            {
                this._falloff_Angle = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TargetableFloat _falloff_Exponent = new Collada141.TargetableFloat { Value = 0D };
        
        /// <summary>
        /// <para>The falloff_exponent is used to specify the amount of attenuation based on the direction of the light.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The falloff_exponent is used to specify the amount of attenuation based on the di" +
            "rection of the light.")]
        [System.Xml.Serialization.XmlElementAttribute("falloff_exponent")]
        public TargetableFloat Falloff_Exponent
        {
            get
            {
                return this._falloff_Exponent;
            }
            set
            {
                this._falloff_Exponent = value;
            }
        }
    }
}
