//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("physics_scene", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("physics_scene", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public partial class Physics_Scene
    {
        
        /// <summary>
        /// <para>The physics_scene element may contain an asset element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The physics_scene element may contain an asset element.")]
        [System.Xml.Serialization.XmlElementAttribute("asset")]
        public Asset Asset { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<InstanceWithExtra> _instance_Force_Field;
        
        /// <summary>
        /// <para>There may be any number of instance_force_field elements.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("There may be any number of instance_force_field elements.")]
        [System.Xml.Serialization.XmlElementAttribute("instance_force_field")]
        public System.Collections.ObjectModel.Collection<InstanceWithExtra> Instance_Force_Field
        {
            get
            {
                return this._instance_Force_Field;
            }
            private set
            {
                this._instance_Force_Field = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Instance_Force_Field collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Instance_Force_FieldSpecified
        {
            get
            {
                return (this.Instance_Force_Field.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Physics_Scene" /> class.</para>
        /// </summary>
        public Physics_Scene()
        {
            this._instance_Force_Field = new System.Collections.ObjectModel.Collection<InstanceWithExtra>();
            this._instance_Physics_Model = new System.Collections.ObjectModel.Collection<Instance_Physics_Model>();
            this._technique = new System.Collections.ObjectModel.Collection<Technique>();
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Instance_Physics_Model> _instance_Physics_Model;
        
        /// <summary>
        /// <para>There may be any number of instance_physics_model elements.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("There may be any number of instance_physics_model elements.")]
        [System.Xml.Serialization.XmlElementAttribute("instance_physics_model")]
        public System.Collections.ObjectModel.Collection<Instance_Physics_Model> Instance_Physics_Model
        {
            get
            {
                return this._instance_Physics_Model;
            }
            private set
            {
                this._instance_Physics_Model = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Instance_Physics_Model collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Instance_Physics_ModelSpecified
        {
            get
            {
                return (this.Instance_Physics_Model.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The technique_common element specifies the physics_scene information for the common profile 
        ///						which all COLLADA implementations need to support.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The technique_common element specifies the physics_scene information for the comm" +
            "on profile which all COLLADA implementations need to support.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("technique_common")]
        public Physics_SceneTechnique_Common Technique_Common { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Technique> _technique;
        
        /// <summary>
        /// <para>This element may contain any number of non-common profile techniques.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("This element may contain any number of non-common profile techniques.")]
        [System.Xml.Serialization.XmlElementAttribute("technique")]
        public System.Collections.ObjectModel.Collection<Technique> Technique
        {
            get
            {
                return this._technique;
            }
            private set
            {
                this._technique = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Technique collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TechniqueSpecified
        {
            get
            {
                return (this.Technique.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        /// <summary>
        /// <para>The extra element may appear any number of times.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The extra element may appear any number of times.")]
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The id attribute is a text string containing the unique identifier of this element. 
        ///					This value must be unique within the instance document. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The id attribute is a text string containing the unique identifier of this elemen" +
            "t. This value must be unique within the instance document. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
        
        /// <summary>
        /// <para>The name attribute is the text string name of this element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The name attribute is the text string name of this element. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
}
