//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Physics_MaterialTechnique_Common", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Physics_MaterialTechnique_Common
    {
        
        /// <summary>
        /// <para>Dynamic friction coefficient</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dynamic friction coefficient")]
        [System.Xml.Serialization.XmlElementAttribute("dynamic_friction")]
        public TargetableFloat Dynamic_Friction { get; set; }
        
        /// <summary>
        /// <para>The proportion of the kinetic energy preserved in the impact (typically ranges from 0.0 to 1.0)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The proportion of the kinetic energy preserved in the impact (typically ranges fr" +
            "om 0.0 to 1.0)")]
        [System.Xml.Serialization.XmlElementAttribute("restitution")]
        public TargetableFloat Restitution { get; set; }
        
        /// <summary>
        /// <para>Static friction coefficient</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Static friction coefficient")]
        [System.Xml.Serialization.XmlElementAttribute("static_friction")]
        public TargetableFloat Static_Friction { get; set; }
    }
}
