//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>Opens a block of COMMON platform-specific data types and technique declarations.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Opens a block of COMMON platform-specific data types and technique declarations.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("profile_COMMON", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("profile_COMMON", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public partial class Profile_COMMON
    {
        
        [System.Xml.Serialization.XmlElementAttribute("asset")]
        public Asset Asset { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Image> _image;
        
        [System.Xml.Serialization.XmlElementAttribute("image")]
        public System.Collections.ObjectModel.Collection<Image> Image
        {
            get
            {
                return this._image;
            }
            private set
            {
                this._image = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Image collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageSpecified
        {
            get
            {
                return (this.Image.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Profile_COMMON" /> class.</para>
        /// </summary>
        public Profile_COMMON()
        {
            this._image = new System.Collections.ObjectModel.Collection<Image>();
            this._newparam = new System.Collections.ObjectModel.Collection<Common_Newparam_Type>();
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Common_Newparam_Type> _newparam;
        
        [System.Xml.Serialization.XmlElementAttribute("newparam")]
        public System.Collections.ObjectModel.Collection<Common_Newparam_Type> Newparam
        {
            get
            {
                return this._newparam;
            }
            private set
            {
                this._newparam = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Newparam collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewparamSpecified
        {
            get
            {
                return (this.Newparam.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>Holds a description of the textures, samplers, shaders, parameters, and passes necessary for rendering this effect using one method.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Holds a description of the textures, samplers, shaders, parameters, and passes ne" +
            "cessary for rendering this effect using one method.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("technique")]
        public Profile_COMMONTechnique Technique { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        /// <summary>
        /// <para>The extra element may appear any number of times.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The extra element may appear any number of times.")]
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The id attribute is a text string containing the unique identifier of this element. 
        ///					This value must be unique within the instance document. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The id attribute is a text string containing the unique identifier of this elemen" +
            "t. This value must be unique within the instance document. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
}
