//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>The instance_physics_material element declares the instantiation of a COLLADA physics_material 
    ///			resource.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("The instance_physics_material element declares the instantiation of a COLLADA phy" +
        "sics_material resource.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("instance_physics_material", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public partial class Instance_Physics_Material : InstanceWithExtra
    {
    }
}
