//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Profile_COMMONTechniqueBlinn", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Profile_COMMONTechniqueBlinn
    {
        
        [System.Xml.Serialization.XmlElementAttribute("emission")]
        public Common_Color_Or_Texture_Type Emission { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ambient")]
        public Common_Color_Or_Texture_Type Ambient { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("diffuse")]
        public Common_Color_Or_Texture_Type Diffuse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("specular")]
        public Common_Color_Or_Texture_Type Specular { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shininess")]
        public Common_Float_Or_Param_Type Shininess { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("reflective")]
        public Common_Color_Or_Texture_Type Reflective { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("reflectivity")]
        public Common_Float_Or_Param_Type Reflectivity { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("transparent")]
        public Common_Transparent_Type Transparent { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("transparency")]
        public Common_Float_Or_Param_Type Transparency { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("index_of_refraction")]
        public Common_Float_Or_Param_Type Index_Of_Refraction { get; set; }
    }
}
