//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Profile_GLESTechniquePass", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Profile_GLESTechniquePass : IGles_Pipeline_Settings
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Fx_Annotate_Common> _annotate;
        
        [System.Xml.Serialization.XmlElementAttribute("annotate")]
        public System.Collections.ObjectModel.Collection<Fx_Annotate_Common> Annotate
        {
            get
            {
                return this._annotate;
            }
            private set
            {
                this._annotate = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Annotate collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnnotateSpecified
        {
            get
            {
                return (this.Annotate.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Profile_GLESTechniquePass" /> class.</para>
        /// </summary>
        public Profile_GLESTechniquePass()
        {
            this._annotate = new System.Collections.ObjectModel.Collection<Fx_Annotate_Common>();
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("color_target")]
        public string Color_Target { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("depth_target")]
        public string Depth_Target { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stencil_target")]
        public string Stencil_Target { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("color_clear")]
        public string Color_Clear { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("depth_clear")]
        public double Depth_Clear { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Depth_Clear property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Depth_ClearSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stencil_clear")]
        public sbyte Stencil_Clear { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Stencil_Clear property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Stencil_ClearSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("draw")]
        public string Draw { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("alpha_func")]
        public Gles_Pipeline_SettingsAlpha_Func Alpha_Func { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("blend_func")]
        public Gles_Pipeline_SettingsBlend_Func Blend_Func { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("clear_color")]
        public Gles_Pipeline_SettingsClear_Color Clear_Color { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("clear_stencil")]
        public Gles_Pipeline_SettingsClear_Stencil Clear_Stencil { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("clear_depth")]
        public Gles_Pipeline_SettingsClear_Depth Clear_Depth { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("clip_plane")]
        public Gles_Pipeline_SettingsClip_Plane Clip_Plane { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("color_mask")]
        public Gles_Pipeline_SettingsColor_Mask Color_Mask { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cull_face")]
        public Gles_Pipeline_SettingsCull_Face Cull_Face { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("depth_func")]
        public Gles_Pipeline_SettingsDepth_Func Depth_Func { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("depth_mask")]
        public Gles_Pipeline_SettingsDepth_Mask Depth_Mask { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("depth_range")]
        public Gles_Pipeline_SettingsDepth_Range Depth_Range { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fog_color")]
        public Gles_Pipeline_SettingsFog_Color Fog_Color { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fog_density")]
        public Gles_Pipeline_SettingsFog_Density Fog_Density { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fog_mode")]
        public Gles_Pipeline_SettingsFog_Mode Fog_Mode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fog_start")]
        public Gles_Pipeline_SettingsFog_Start Fog_Start { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fog_end")]
        public Gles_Pipeline_SettingsFog_End Fog_End { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("front_face")]
        public Gles_Pipeline_SettingsFront_Face Front_Face { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("texture_pipeline")]
        public Gles_Pipeline_SettingsTexture_Pipeline Texture_Pipeline { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("logic_op")]
        public Gles_Pipeline_SettingsLogic_Op Logic_Op { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_ambient")]
        public Gles_Pipeline_SettingsLight_Ambient Light_Ambient { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_diffuse")]
        public Gles_Pipeline_SettingsLight_Diffuse Light_Diffuse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_specular")]
        public Gles_Pipeline_SettingsLight_Specular Light_Specular { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_position")]
        public Gles_Pipeline_SettingsLight_Position Light_Position { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_constant_attenuation")]
        public Gles_Pipeline_SettingsLight_Constant_Attenuation Light_Constant_Attenuation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_linear_attenutation")]
        public Gles_Pipeline_SettingsLight_Linear_Attenutation Light_Linear_Attenutation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_quadratic_attenuation")]
        public Gles_Pipeline_SettingsLight_Quadratic_Attenuation Light_Quadratic_Attenuation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_spot_cutoff")]
        public Gles_Pipeline_SettingsLight_Spot_Cutoff Light_Spot_Cutoff { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_spot_direction")]
        public Gles_Pipeline_SettingsLight_Spot_Direction Light_Spot_Direction { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_spot_exponent")]
        public Gles_Pipeline_SettingsLight_Spot_Exponent Light_Spot_Exponent { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_model_ambient")]
        public Gles_Pipeline_SettingsLight_Model_Ambient Light_Model_Ambient { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("line_width")]
        public Gles_Pipeline_SettingsLine_Width Line_Width { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("material_ambient")]
        public Gles_Pipeline_SettingsMaterial_Ambient Material_Ambient { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("material_diffuse")]
        public Gles_Pipeline_SettingsMaterial_Diffuse Material_Diffuse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("material_emission")]
        public Gles_Pipeline_SettingsMaterial_Emission Material_Emission { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("material_shininess")]
        public Gles_Pipeline_SettingsMaterial_Shininess Material_Shininess { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("material_specular")]
        public Gles_Pipeline_SettingsMaterial_Specular Material_Specular { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("model_view_matrix")]
        public Gles_Pipeline_SettingsModel_View_Matrix Model_View_Matrix { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("point_distance_attenuation")]
        public Gles_Pipeline_SettingsPoint_Distance_Attenuation Point_Distance_Attenuation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("point_fade_threshold_size")]
        public Gles_Pipeline_SettingsPoint_Fade_Threshold_Size Point_Fade_Threshold_Size { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("point_size")]
        public Gles_Pipeline_SettingsPoint_Size Point_Size { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("point_size_min")]
        public Gles_Pipeline_SettingsPoint_Size_Min Point_Size_Min { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("point_size_max")]
        public Gles_Pipeline_SettingsPoint_Size_Max Point_Size_Max { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("polygon_offset")]
        public Gles_Pipeline_SettingsPolygon_Offset Polygon_Offset { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("projection_matrix")]
        public Gles_Pipeline_SettingsProjection_Matrix Projection_Matrix { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("scissor")]
        public Gles_Pipeline_SettingsScissor Scissor { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shade_model")]
        public Gles_Pipeline_SettingsShade_Model Shade_Model { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stencil_func")]
        public Gles_Pipeline_SettingsStencil_Func Stencil_Func { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stencil_mask")]
        public Gles_Pipeline_SettingsStencil_Mask Stencil_Mask { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stencil_op")]
        public Gles_Pipeline_SettingsStencil_Op Stencil_Op { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("alpha_test_enable")]
        public Gles_Pipeline_SettingsAlpha_Test_Enable Alpha_Test_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("blend_enable")]
        public Gles_Pipeline_SettingsBlend_Enable Blend_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("clip_plane_enable")]
        public Gles_Pipeline_SettingsClip_Plane_Enable Clip_Plane_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("color_logic_op_enable")]
        public Gles_Pipeline_SettingsColor_Logic_Op_Enable Color_Logic_Op_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("color_material_enable")]
        public Gles_Pipeline_SettingsColor_Material_Enable Color_Material_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cull_face_enable")]
        public Gles_Pipeline_SettingsCull_Face_Enable Cull_Face_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("depth_test_enable")]
        public Gles_Pipeline_SettingsDepth_Test_Enable Depth_Test_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dither_enable")]
        public Gles_Pipeline_SettingsDither_Enable Dither_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fog_enable")]
        public Gles_Pipeline_SettingsFog_Enable Fog_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("texture_pipeline_enable")]
        public Gles_Pipeline_SettingsTexture_Pipeline_Enable Texture_Pipeline_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_enable")]
        public Gles_Pipeline_SettingsLight_Enable Light_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lighting_enable")]
        public Gles_Pipeline_SettingsLighting_Enable Lighting_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("light_model_two_side_enable")]
        public Gles_Pipeline_SettingsLight_Model_Two_Side_Enable Light_Model_Two_Side_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("line_smooth_enable")]
        public Gles_Pipeline_SettingsLine_Smooth_Enable Line_Smooth_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("multisample_enable")]
        public Gles_Pipeline_SettingsMultisample_Enable Multisample_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("normalize_enable")]
        public Gles_Pipeline_SettingsNormalize_Enable Normalize_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("point_smooth_enable")]
        public Gles_Pipeline_SettingsPoint_Smooth_Enable Point_Smooth_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("polygon_offset_fill_enable")]
        public Gles_Pipeline_SettingsPolygon_Offset_Fill_Enable Polygon_Offset_Fill_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("rescale_normal_enable")]
        public Gles_Pipeline_SettingsRescale_Normal_Enable Rescale_Normal_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sample_alpha_to_coverage_enable")]
        public Gles_Pipeline_SettingsSample_Alpha_To_Coverage_Enable Sample_Alpha_To_Coverage_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sample_alpha_to_one_enable")]
        public Gles_Pipeline_SettingsSample_Alpha_To_One_Enable Sample_Alpha_To_One_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sample_coverage_enable")]
        public Gles_Pipeline_SettingsSample_Coverage_Enable Sample_Coverage_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("scissor_test_enable")]
        public Gles_Pipeline_SettingsScissor_Test_Enable Scissor_Test_Enable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stencil_test_enable")]
        public Gles_Pipeline_SettingsStencil_Test_Enable Stencil_Test_Enable { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The sid attribute is a text string value containing the sub-identifier of this element. 
        ///											This value must be unique within the scope of the parent element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The sid attribute is a text string value containing the sub-identifier of this el" +
            "ement. This value must be unique within the scope of the parent element. Optiona" +
            "l attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("sid")]
        public string Sid { get; set; }
    }
}
