//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    /// <summary>
    /// <para>This element allows for describing simulated bodies that do not deform. These bodies may or may 
    ///			not be connected by constraints (hinge, ball-joint etc.).  Rigid-bodies, constraints etc. are 
    ///			encapsulated in physics_model elements to allow for instantiating complex models.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"This element allows for describing simulated bodies that do not deform. These bodies may or may not be connected by constraints (hinge, ball-joint etc.). Rigid-bodies, constraints etc. are encapsulated in physics_model elements to allow for instantiating complex models.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("rigid_body", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("rigid_body", Namespace="http://www.collada.org/2005/11/COLLADASchema")]
    public partial class Rigid_Body
    {
        
        /// <summary>
        /// <para>The technique_common element specifies the rigid_body information for the common profile which all 
        ///						COLLADA implementations need to support.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The technique_common element specifies the rigid_body information for the common " +
            "profile which all COLLADA implementations need to support.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("technique_common")]
        public Rigid_BodyTechnique_Common Technique_Common { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Technique> _technique;
        
        /// <summary>
        /// <para>This element may contain any number of non-common profile techniques.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("This element may contain any number of non-common profile techniques.")]
        [System.Xml.Serialization.XmlElementAttribute("technique")]
        public System.Collections.ObjectModel.Collection<Technique> Technique
        {
            get
            {
                return this._technique;
            }
            private set
            {
                this._technique = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Technique collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TechniqueSpecified
        {
            get
            {
                return (this.Technique.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Rigid_Body" /> class.</para>
        /// </summary>
        public Rigid_Body()
        {
            this._technique = new System.Collections.ObjectModel.Collection<Technique>();
            this._extra = new System.Collections.ObjectModel.Collection<Extra>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Extra> _extra;
        
        /// <summary>
        /// <para>The extra element may appear any number of times.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The extra element may appear any number of times.")]
        [System.Xml.Serialization.XmlElementAttribute("extra")]
        public System.Collections.ObjectModel.Collection<Extra> Extra
        {
            get
            {
                return this._extra;
            }
            private set
            {
                this._extra = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Extra collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtraSpecified
        {
            get
            {
                return (this.Extra.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>The sid attribute is a text string value containing the sub-identifier of this element. This 
        ///					value must be unique within the scope of the parent element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The sid attribute is a text string value containing the sub-identifier of this el" +
            "ement. This value must be unique within the scope of the parent element. Optiona" +
            "l attribute.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("sid")]
        public string Sid { get; set; }
        
        /// <summary>
        /// <para>The name attribute is the text string name of this element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The name attribute is the text string name of this element. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
}
