//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.560.0 using the following command:
// xscgen -o Collada141 --nc=true --sf .\collada_schema_1_4_1_ms.xsd
namespace Collada141
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.560.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Visual_SceneEvaluate_Scene", Namespace="http://www.collada.org/2005/11/COLLADASchema", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Visual_SceneEvaluate_Scene
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Visual_SceneEvaluate_SceneRender> _render;
        
        /// <summary>
        /// <para>The render element describes one effect pass to evaluate the scene.
        ///									There must be at least one render element.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The render element describes one effect pass to evaluate the scene. There must be" +
            " at least one render element.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("render")]
        public System.Collections.ObjectModel.Collection<Visual_SceneEvaluate_SceneRender> Render
        {
            get
            {
                return this._render;
            }
            private set
            {
                this._render = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Visual_SceneEvaluate_Scene" /> class.</para>
        /// </summary>
        public Visual_SceneEvaluate_Scene()
        {
            this._render = new System.Collections.ObjectModel.Collection<Visual_SceneEvaluate_SceneRender>();
        }
        
        /// <summary>
        /// <para>The name attribute is the text string name of this element. Optional attribute.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The name attribute is the text string name of this element. Optional attribute.")]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
}
